version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
              - save_hello_world_output
      - Use_command

commands:
  print_pipeline_id:
    description: "Print pipeline id"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID


jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - output.txt
  print_output_file:
        docker:
          - image: circleci/node:10.16.3
        steps:
          - attach_workspace:
              at: .
          - run: cat output.txt
  Use_command:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - print_pipeline_id



            
     